language: 'node_js'
python:
- '2.7'
node_js:
- '10'
install:
- nvm install 8.10
- pip install awscli
- pip install aws-sam-cli
script:
- cd backend
- sam validate
- sam package --template-file template.yaml --s3-bucket osu-so-serverless-builds --output-template-file
  packaged.yaml
- cd ../
- npm install
- npm run build

deploy:
- provider: script
  script: >-
    cd backend;
    sam deploy --template-file ./packaged.yaml --stack-name auth --capabilities CAPABILITY_IAM;
  skip-cleanup: true
  on:
    branch: master
- provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
