AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Meters

  Simple upload route for meter read images

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors: 
      AllowOrigin: "'http://localhost:8080'"
    BinaryMediaTypes:
      - image~1gif
      - image~1png
      - image~1jpeg
      - application/octet-stream
      - multipart/form-data
Parameters:
  LambdaCommonLayer:
    Type: String
    Default: arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:72

Resources:
  Upload:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: app.upload
      Layers:
        - !Ref LambdaCommonLayer
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: post
